version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - afyadb-network
    healthcheck:
      test: [ "CMD-SHELL", "mongosh --quiet --eval \"db.runCommand({ ping: 1 }).ok\" | grep 1" ]
      interval: 10s
      timeout: 10s
      retries: 5

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    restart: always
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
      - DATA_DIR=/tmp/localstack_data
      - EDGE_PORT=4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DEBUG=1
    volumes:
      - localstack_data:/tmp/localstack_data
    networks:
      - afyadb-network
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:4566/_localstack/health || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 5

  nestjs:
    build: .
    container_name: nestjs
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/afyadb
      - S3_ENDPOINT=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - S3_BUCKET=my-bucket
    depends_on:
      mongodb:
        condition: service_healthy
      localstack:
        condition: service_healthy
    networks:
      - afyadb-network

volumes:
  mongo_data:
  localstack_data:


networks:
  afyadb-network:
    driver: bridge
